# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: make static directory available on /github/workspace
        run: |
          echo "realpath static"
          realpath static
        continue-on-error: true

      - name: Check files exist
        run: |
          echo "-- ls static: --"
          ls -la static
        continue-on-error: true

      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # BUILD_DIR: /github/workspace
          # Use automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

